n =(input('Digite seu valor:'))
# print(type(n),n.isnumeric(),n.isalpha())
# print(type(n),n.isalnum(),n.isnumeric(),n.isalpha(),n.isdecimal(),n.islower(),n.isupper())
print(type(n),('O valor é lower case?'),n.islower())
print(type(n),n.isalnum())
print(type(n),n.isnumeric())
print(type(n),n.isalpha())
print(type(n),n.isdecimal())
print(type(n),n.isupper())
print(type(n),n.isascii())
