from classs005 import CarrinhoDeCompras, Produto
carrinho = CarrinhoDeCompras()
p1 = Produto('Macarrão', 13)
p2 = Produto('Computador', 2500)
p3 = Produto('Xbox', 3000)
carrinho.inserir_produto(p1)
carrinho.inserir_produto(p2)
carrinho.inserir_produto(p3)
carrinho.inserir_produto(p1)
carrinho.lista_produtos()
print(f'O valor total foi de {carrinho.soma_total()}')